class ClothingData {
  static const List<String> clothingDescriptions = [
    'Comfortable and casual',
    'Classic denim fit',
    'Warm and stylish',
    'Cozy and soft',
    'Elegant and flowing',
    'Stylish and versatile',
    'Light and airy',
    'Casual and cool',
    'Warm and cozy',
    'Casual yet smart',
    'Light and breathable',
    'Stretchy and form-fitting',
    'Warm and protective',
    'Casual and trendy',
    'Comfortable and relaxed',
    'Smart and casual',
    'Sporty and relaxed',
    'Durable and stylish',
    'Functional and roomy',
    'Formal and fitted',
    'Casual and cool',
    'Warm and comfortable',
    'Light and protective',
    'Cozy and stylish',
    'Casual and comfortable',
    'Sporty and practical',
    'Beach-ready',
    'Protective and durable',
    'Light and airy',
    'Beach-ready wrap',
    'Stylish and wide-legged',
    'Functional and durable',
    'Formal and fitted',
    'Warm and elegant',
    'Trendy and casual',
    'Water-resistant and protective',
    'Warm and cozy',
    'Relaxed and flowy',
    'Traditional and elegant',
    'Comfortable and soft',
    'Soft and absorbent',
    'Relaxed and cozy',
    'Comfortable and casual',
    'Essential and supportive',
    'Pool or beach-ready'
  ];
  static const List<String> names = [
    "Alpha",
    "Beta",
    "Gamma",
    "Delta",
    "Epsilon",
    "Zeta",
    "Eta",
    "Theta",
    "Iota",
    "Kappa",
    "Lambda",
    "Mu",
    "Nu",
    "Xi",
    "Omicron",
    "Pi",
    "Rho",
    "Sigma",
    "Tau",
    "Upsilon",
    "Phi",
    "Chi",
    "Psi",
    "Omega",
    "Zenith",
    "Nova",
    "Orion",
    "Pulsar",
    "Quasar",
    "Nebula",
    "Galaxy",
    "Cosmos",
    "Astro",
    "Lunar",
    "Solar",
    "Comet",
    "Meteor",
    "Eclipse",
    "Aurora",
    "Vortex",
    "Zenith",
    "Tide",
    "Cascade",
    "Horizon",
  ];
}
